### PR TITLE
feat(api): export SDK

### PR DESCRIPTION
**Pull request by yoitsro**
| 🚥 Resolves https://github.com/readmeio/api/issues/821 |
| :------------------- |

## 🧰 Changes

In some use cases, the SDK class needs to be instantiated several times.

For instance, in a multi-tenancy scenario, there may be multiple instances of the same API server, but serving different tenants' data from different base URLs. In this case, we need to instantiate multiple clients with different server URLs.

## 🧬 QA & Testing

The unit test fixtures have been updated accordingly to reflect that the SDK is now exported.

### CODE REVIEW

**Review by kanadgupta — CHANGES_REQUESTED** [review]
hi, thanks so much for this contribution! unfortunately when compiling TS into CJS and ESM, files with both default and non-default exports typically lead to typing issues in certain environments. we don't have great test coverage on this front quite yet unfortunately.

what if the class was the default export from a new `src/sdk.ts` file and the IIFE in `src/index.ts` imports that?[^1]

[^1]: first discussed [here](https://github.com/readmeio/api/issues/821#issuecomment-1839242629)

**Comment by yoitsro** [comment]
Yeah, I saw that discussion after submitting the PR but didn't have time to sort it. Let me take a quick look at it.

**Comment by yoitsro** [comment]
Here are the changes. Once they're good, I'll squash the commits down (or I guess you could do that too if required).

**Review by kanadgupta — APPROVED** [review]
thanks again, this looks great!

**Comment by kanadgupta** [comment]
> I'll squash the commits down (or I guess you could do that too if required).

and we'll take care of squashing when we merge, thanks!

**Review by erunion — APPROVED** [review]
thanks for this!

**Pull request merged**
