### PR TITLE
fix: use dynamic import for node-specific libraries

### PR DESCRIPTION
**Pull request by kanadgupta**
## 🧰 Changes

I went down a little rabbit hole to see how it would work to load these SDKs in a browser environment as part of the docs I want to write up. The closest I got to success was this error (even with a webpack config and various tweaks to it):

CleanShot 2023-11-16 at 10 31 50@2x

Looks like the same error alluded to here: https://github.com/readmeio/api/issues/604#issuecomment-1516682177

I figured that by only loading the node-specific libraries within the function that needs it, we might be able to successfully run this in a browser environment?

## 🧬 QA & Testing

I was unable to successfully `npm link` this into my setup in a way that played nicely with webpack so hard to see if this will work. Open to other ideas here!

### CODE REVIEW

**Comment by kanadgupta** [comment]
Update: chatted with @erunion about this a while back and we might be able to bring in the `datauri` methods that we use directly — will pick this up when I have capacity again!

**Comment by joaocanaverde-blue** [comment]
@kanadgupta @erunion Hi! Any chance this can be merged? Happy to contribute if anything is needed.

**Comment by kanadgupta** [comment]
@erunion ready for review again. I tried playing around with vendoring `datauri` but it felt like overkill since we'd need to create a separate subpackage for it since it's used in both `core` and `testing-utils`

**Comment by kanadgupta** [comment]
Hi there @joaocanaverde-blue — [`v7.0.0-beta.11`](https://github.com/readmeio/api/releases/tag/v7.0.0-beta.11) includes this change.

**Pull request merged**
